// Dicionário de correções de acentuação (consolidado de todos os arquivos)
export const accentCorrections: Record<string, string> = {
  periodo: "Período",
  analise: "Análise",
  analisado: "Analisado",
  tendencias: "Tendências",
  crescimento: "Crescimento",
  percentual: "Percentual",
  observacoes: "Observações",
  previsao: "Previsão",
  proximos: "Próximos",
  dias: "Dias",
  produtos: "Produtos",
  esperados: "Esperados",
  vender: "Vender",
  receita: "Receita",
  prevista: "Prevista",
  pedidos: "Pedidos",
  previstos: "Previstos",
  risco: "Risco",
  estoque: "Estoque",
  padroes: "Padrões",
  identificados: "Identificados",
  recomendacoes: "Recomendações",
  acao: "Ação",
  acoes: "Ações",
  reabastecimento: "Reabastecimento",
  alertas: "Alertas",
  financeiro: "Financeiro",
  relatorio: "Relatório",
  inicio: "Início",
  fim: "Fim",
  total: "Total",
  geral: "Geral",
  taxa: "Taxa",
  data: "Data",
  prioritaria: "Prioritária",
  secundarias: "Secundárias",
  situacao: "Situação",
  raciocinio: "Raciocínio",
  metricas: "Métricas",
  medio: "Médio",
  media: "Média",
  periodo_analisado: "Período",
};

export const periodoOptions = [
  { id: "mes_atual", value: "mes_atual", nome: "Mês Atual" },
  { id: "3_meses", value: "3_meses", nome: "Últimos 3 Meses" },
  { id: "6_meses", value: "6_meses", nome: "Últimos 6 Meses" },
  { id: "ano", value: "ano", nome: "Último Ano" },
];

