import type { Metadata } from "next";
import { Lexend, Nunito} from "next/font/google";
import "./globals.css";

const lexend = Lexend({
    subsets: ["latin"]
  });

const nunito = Nunito({
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`antialiased`}>
        {children}
      </body>
    </html>
  );
}
